FROM golang:latest

# Copy the local package files to the container’s workspace.
COPY . /go_projects/src/go-webapp-sample/

# Build the golang-docker command inside the container.
RUN go install github.com/ybkuroki/go-webapp-sample@latest

# Run the golang-docker command when the container starts.
CMD ["go-webapp-sample"] 

# http server listens on port 8080.
EXPOSE 8080
